name: Publish to NPM
on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: Publish
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: pnpm build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
